#!/usr/bin/python
#
#   This hacky little script wraps an HTTP request in proxy protocol and outputs the response.
#   Run with -h flag for usage. This is a nice script to use when performing health checks on
#   servers that require proxy protocol. Using [-s|--status-code] we will receive the response
#   status code back. Ex:
#
#   ./rubber http://server:8080/health -X GET --status-code
#
#

# Didn't use docopt to avoid external dependencies.. very ugly
import argparse
try:
    from urlparse import urlparse
except ImportError as err:
    from urllib.parse import urlparse
import socket
import ssl

SUPPORTED_VERBS = ["POST", "PUT", "GET", "DELETE"]


class ProxyProtocolWrapper(object):
    def __init__(self, **kwargs):
        self._process_url(kwargs.get("url"), kwargs.get("source"), kwargs.get("port"), kwargs.get("source_port"))
        self.verbose = kwargs.get("verbose")
        self.send_proxy = kwargs.get("no_proxy") is False
        self.data = kwargs.get("data")
        self.verb = kwargs.get("verb")
        self.status_code = kwargs.get("status_code")
        self.headers = kwargs.get("headers")
        self.verbose_string = ""

        if not self.verb or self.verb not in SUPPORTED_VERBS:
            self.verb = "GET"

    def _process_url(self, url, source=None, port=None, source_port=None):
        """ Processes source and destination host and port info. """
        # Defaults to http if scheme doesn't exist
        if not url.startswith("http"):
            url = "http://{0}".format(url)

        self.url = urlparse(url)
        self.path = self.url.path

        if not self.path:
            self.path = "/"
        self.source_port = self._default_port(source_port)
        self.dest_host, self.port = self.url.netloc.partition(":")[::2]
        self.dest_ip = socket.gethostbyname(self.dest_host)

        if not self.port:
            self.port = self._default_port(port)
        self.source = source

        if source:
            self.source_ip = socket.gethostbyname(self.source)
        else:
            self.source_ip = "127.0.0.1"

    def _default_port(self, port=None):
        """ Defaults a port in order of priority. This makes using this tool more flexible. """

        scheme_port = {"http": 80, "https": 443}.get(self.url.scheme)
        if not port:
            if not scheme_port:
                # Arbitrary default if nothing is set
                port = 80
            else:
                port = scheme_port
        return port

    def _build_proxy_string(self):
        """ Generates the proxy protocol string """

        data = map(str, ("PROXY", "TCP4", self.source_ip, self.dest_ip, self.source_port, self.port))
        proxy = ' '.join(data) + '\r\n'
        self.verbose_string += proxy
        return proxy

    def _connect(self):
        """
            Creates the TCP connection, sends the proxy protocol string then
            upgrades the socket to SSL if necessary.
        """

        self.connection = socket.create_connection((self.dest_host, self.port))

        if self.send_proxy:
            self.connection.send(self._build_proxy_string().encode())

        if self.url.scheme == "https":
            self.connection = ssl.wrap_socket(self.connection)

    def _build_request(self):
        data = ""
        formatted_headers = ""

        if self.data:
            data = "Content-Type: application/json\r\n" \
                   "Content-Length: {0}\r\n".format(len(self.data))

        if self.headers:
            for header in self.headers:
                formatted_headers += header + "\r\n"

        request = "{0} {1} HTTP/1.1\r\n" \
                  "Host: {2}\r\n" \
                  "Connection: close\r\n" \
                  "{3}{4}\r\n".format(self.verb.upper(), self.path, self.dest_host, data, formatted_headers)

        self.verbose_string += request
        return request

    def request(self):

        self._connect()
        self.connection.send(self._build_request().encode())

        if self.data:
            self.connection.send(self.data.encode())

        response = ""
        while True:
            part = self.connection.recv(4096)
            if not part:
                break
            else:
                response += part.decode()
        self.connection.close()

        if self.status_code:
            response = response.split(" ")[1]

        if self.verbose:
            print(self.verbose_string)

        return response

usage_msg= """
            rubber <URL> [options]
                        -h for help
           """

parser = argparse.ArgumentParser(usage=usage_msg)
parser.add_argument("url", type=str, action="store", help="URL to send request to")
parser.add_argument("-X", type=str, metavar="VERB", action="store", help="HTTP verb, Supported: GET, POST, PUT, and DELETE")
parser.add_argument("-s", "--status-code", action="store_true", help="Pass option to return only the status code")
parser.add_argument("--source", type=str, action="store", help="Souce host for proxy")
parser.add_argument("-p", "--port", type=int, action="store", help="Destination port to communicate on")
parser.add_argument("--source-port", type=int, action="store", help="Source port for proxy")
parser.add_argument("-d", "--data", type=str, action="store", help="Data to send with the http request")
parser.add_argument("-H", "--headers", type=str, nargs="+", action="store", help="Headers to send in http request")
parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output while making request")
parser.add_argument("-n", "--no-proxy", action="store_true", help="Send request without proxy protocol")
args = vars(parser.parse_args())

proxy_wrapper = ProxyProtocolWrapper(**args)
print(proxy_wrapper.request())
